version: '3.8'

services:
  laravel-backend:
    build:
      context: ./FlagsApp
    container_name: laravel_backend
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:m0wWRW65OG/dWXqGb5OkopALXVFWBzQQlCoIYsrArEg=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./laravel-backend:/var/www
      - ./laravel-backend/public:/var/www/html
    depends_on:
      - db

  vue-frontend:
    build:
      context: ./FlagsFE
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
